### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [CupricReki/zsh-bw-completion#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by CupricReki** [comment]
Added MIT License

Appreciate the heads up

**Comment by CupricReki** [comment]
Added MIT License

Appreciate the heads up

**Comment by CupricReki** [comment]
Looks like the bw cli utility actually has autocomplete built into it now, you just need to make zsh aware of it. 

https://github.com/bitwarden/cli/pull/137

`eval "$(bw completion --shell zsh); compdef _bw bw;"`

**Comment by CupricReki** [comment]
Seb's version seems to work a lot better than the one merged into bitwarden. My repos still seems like the right option.
